version: '3.1'
services:
  # odoo web app
  odoo-web:
    container_name: odoo-web
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile.dev
    depends_on:
    - odoo-db
    volumes:
    - odoo-web-data:/var/lib/odoo
    - ./modules:/mnt/extra-addons
    # - .:/mnt:cached # update this to wherever you want VS Code to mount the folder of your project
    ports:
    - "8069:8069"
    expose:
    - 8069
    environment:
    - HOST=odoo-db
    - USER=odoo
    - PASSWORD=myodoo
    restart: always

  # postgres db
  odoo-db:
    container_name: odoo-db
    image: postgres:15
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_PASSWORD=myodoo
    - POSTGRES_USER=odoo
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always

volumes:
  odoo-web-data:
  odoo-db-data: