version: '3.1'
services:
  # odoo web app
  web:
    container_name: odoo-web
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile.dev
    depends_on:
      - mydb
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./modules:/mnt/extra-addons
    ports:
      - "8069:8069"
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo

  # postgres db
  mydb:
    container_name: odoo-db
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data: