# -*- coding: utf-8 -*-
from . import cpms_associate_profile
from . import client_profile
from . import corporate_officer
from . import cpms_capitalization
from . import escalation
from . import organization_type
from . import cpms_job_title
from . import cpms_cluster
from . import cpms_team
from . import cpms_sole_proprietor
from . import cpms_general_partnership
from . import cpms_general_professional_partnership
from . import cpms_domestic_stock
from . import cpms_domestic_nsnp_corp
from . import cpms_foriegn_corp
from . import cpms_foreign_nsnp_corp
from . import cpms_roqh_foreign_corp
from . import cpms_representative_office
from . import cpms_capital_sole_proprietor
from . import cpms_capital_general_partnership
from . import cpms_capital_general_professional_partnership
from . import cpms_capital_domestic_nsnp_corp
from . import cpms_capital_foreign_corp
from . import cpms_capital_foreign_nsnp
from . import cpms_capital_roqh_foreign_corp
from . import cpms_capital_representative_office
from . import cpms_tax_type
from . import cpms_supervisor