FROM odoo:16

WORKDIR /etc/odoo
COPY ./.docker/modules_requirements.txt /etc/odoo/requirements.txt

USER root
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y git && apt-get install -y sudo
RUN usermod -aG sudo odoo
RUN pip install -r /etc/odoo/requirements.txt

# create vscode user then add to docker group
RUN useradd -s /bin/bash -m vscode \
 && groupadd docker \
 && usermod -aG docker vscode

USER vscode